### ISSUE TITLE
https://www.nytimes.com isn't working

### ISSUE THREAD

**Issue by toklok** [rviscomi/crux-dash-launcher#1]
https://datastudio.google.com/u/0/reporting/bbc5698d-57bb-4969-9e07-68810b9fa348/page/keDQB?params=%7B%22origin%22:%22https:%2F%2Fwww.nytimes.com%22%7D

It doesn't appear this is working anymore, maybe you know about this?  maybe you don't.

**Comment by rviscomi** [comment]
+1 thanks for reporting this @toklok! I was able to reproduce this as well. The issue had to do with the connector that the dashboard was built on using an older version of the origin cache. I've hopefully synced the dashboard with the version of the connector everyone uses from g.co/chromeuxdash, so this launcher should be working now. Please give it a test and let me know if you're still having issues: https://rviscomi.github.io/crux-dash-launcher/index.html?https://www.nytimes.com
